using System;
using System.Collections.Frozen;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Netway.AuditableEntity.SourceGenerator;

[Generator]
public class AuditableGenerator : ISourceGenerator
{

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not SyntaxReceiver receiver)
            return;

        var file = context.AdditionalFiles
            .FirstOrDefault(f => f.Path.EndsWith("AuditFields.txt", StringComparison.OrdinalIgnoreCase));


        var text = file.GetText(context.CancellationToken)?.ToString();


        var fieldsFromFile = text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(l =>
            {
                var parts = l.Split(':');
                return parts.Length == 2 ? (Type: parts[0].Trim(), Name: parts[1].Trim()) : (null, null);
            })
            .Where(t => t.Name != null)
            .ToList();
        
        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                continue;

            if (!symbol.GetAttributes().Any(ad => ad.AttributeClass?.Name == "AuditableAttribute"))
                continue;

            var existingMembers = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Select(p => p.Name)
                .ToFrozenSet(StringComparer.OrdinalIgnoreCase);

            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : $"namespace {symbol.ContainingNamespace};";
            var className = symbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine(ns);
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");

            foreach (var f in fieldsFromFile)
            {
                if (!existingMembers.Contains(f.Name))
                {
                    sb.AppendLine($"    public {f.Type} {f.Name} {{ get; set; }}");
                }
            }

            sb.AppendLine("}");

            context.AddSource($"{className}.Audit.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }


}
